package:
  name: morph
  version: "0.1.1"

source:
  path: .

build:
  script:
    - mkdir -p $PREFIX/lib/mojo
    - cp -r morph $PREFIX/lib/mojo/

requirements:
  host:
    - mojo ==1.0.0b1
  run:
    - mojo ==1.0.0b1

about:
  summary: Reflection-powered serialization, deserialization, and validation for Mojo
  license: MIT
